server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: uses-service
          uri: https://github.com/zyimy/micros
          search-paths: config-data
  application:
    name: config-server        
          
             
